### ISSUE TITLE
is not a registered Object. 

### ISSUE THREAD

**Issue by marinsiebert** [marinsiebert/arctodus#1]
The porosity userobject is not registered when running an inputfile. Compiling runs without issues. 
Registering the userobject leads to several error-messages.

**Comment by mcacace** [comment]
You just create a pure virtual class. It does nothing and need to be inherited. You cannot register pure classes. Look at porosity constant in Golem for an example on how to inherit and register child classes

**Comment by marinsiebert** [comment]
I now created a porosityConstant,  inherited from porosity and registered the respective class - the error message remains the same: 
A 'arctodusPorosity' is not a registered Object. 
Do I need to register it explicitly in the App.C?

**Comment by mcacace** [comment]
It seems fine to me. Can you clean and make it again? I will try to clone the repo and see the problem later today

**Comment by marinsiebert** [comment]
Did so, still the same issue. Also tried clobberall to no avail. 
Please find attached the dummy input file I used for testing.
Is it possible that the issue lies with my MOOSE distro? I am using the the Conda Environment with mambaforge3.

[mesh.txt](https://github.com/marinsiebert/arctodus/files/9920331/mesh.txt)

**Comment by mcacace** [comment]
Ah ... it was not a problem while compiling ... 
  [./porosity]
    type = arctodusPorosity
  [../]
should be 
  [./porosity]
    type = arctodusPorosityConstant
  [../]

As said, arctodusProsity is a pure virtual class ...

**Comment by marinsiebert** [comment]
ah, indeed. I checked everything BUT the input file.
