### ISSUE TITLE
Mechanics

### ISSUE THREAD

**Issue by marinsiebert** [marinsiebert/arctodus#2]
Currently investigating strange behaviour of my vertical stresses, as can be seen in the image below. I am assuming it is related to improper boundary conditions, so far I was not able to resolve the issue though, project files are attached.  
[THMsingle2D_steady.zip](https://github.com/marinsiebert/arctodus/files/10851217/THMsingle2D_steady.zip)
The TH components work fine so far, although there is an issue with the way capillary pressures are implemented in the PorousFlow module, I opened a disscusion in the hopes that someone may help me out there. 

![image](https://user-images.githubusercontent.com/113979717/221881880-1ad9796c-9add-41f3-b426-be4a970cb292.png)

**Comment by mcacace** [comment]
What exactly is wrong?

**Comment by marinsiebert** [comment]
Looking at the vertical stress there are apparently interchanging fluctuations of few 100 Pa between neighbouring cells, I am assuming it should be more evenly distributed with depth, like below the horizontal stress. The horizontal displacements of the sides of the model are fixed with a DirichletBC = 0. No matter the change in the BC for the vertical displacements the results look like above or worse. The contrast at the lowermost is due to a fast increase in water saturation.

You do not think this looks implausible? 

![image](https://user-images.githubusercontent.com/113979717/221887157-155a4131-1bfd-4a8d-b3cd-5aa6a74bd32f.png)

**Comment by mcacace** [comment]
Are you solving for gravity in the simulation? This might explain your "weird behaviour"

**Comment by marinsiebert** [comment]
I do, however I am uncertain as to how that would result in the observed fluctuations.

**Comment by marinsiebert** [comment]
Could you elaborate on that?  I am applying the gravity simply by setting the global parameter. There is also an option to use a gravity kernel which functions as a body force and actually produces fine results. However this Kernels requires a Materialproperty density which is generated by a GenericConstantMaterial and therefore does not fit the purpose of this model in the long term.

**Comment by mcacace** [comment]
So, the global parameter only initializes the values of your auxvariable, but that does not mean you are computing the gravity in the calculation. You need to add the relevant kernel and of course, you would need to set a value for the density of your rock or rock+fluid system (this gives the load).

**Comment by marinsiebert** [comment]
Thank you for the clarification.
